name: Laravel

on:
  push:
    branches: [ master ]

jobs:
  deploy-laravel:

    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /var/www/ticket/
            git checkout -f master
            git pull origin master
